### PR TITLE
Add Flatpak talk to allow flatpak-spawn to work

### LINKED ISSUE #227: Update first_run.txt about --talk-name=org.freedesktop.Flatpak
`first_run.txt` suggests using `flatpak-spawn --host` which is not possible in the default configuration.

Although flatpak-spawn hints at `org.freedesktop.Flatpak`, `first_run.txt` should still be more informative on the matter.

### PR DESCRIPTION
**Pull request by cardil**
## Changes

 - Allow flatpak-spawn to work by adding Flatpak talk-name, as [first_run.txt](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/blob/4ebfcd1b304f826f0b7269e6357c8056820b7dfa/first_run.txt#L15) suggest

Fixes #227

### CODE REVIEW

**Comment by cardil** [comment]
Ref: https://github.com/flatpak/flatpak/issues/5538

**Comment by xanscale** [comment]
Spawn are considered a security issue and should be used only if is strictly required.

Why you need it?

PS consider I'm working to update first run txt to remove it reference

**Comment by cardil** [comment]
I need it to call `zsh` from the host machine in Terminal, as described in: 

https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/blob/4ebfcd1b304f826f0b7269e6357c8056820b7dfa/first_run.txt#L17-L18

This is IDE, and more over, this is an integrated Terminal in it. Of course, I can hurt the host OS, if I don't know what I'm doing, but if so, I shouldn't be developing software or using the Terminal. There's no point of using Terminal inside the sandbox.

**Comment by xanscale** [comment]
First you can't use first-run.txt, it's just a file

Second integrated terminal can be used to run Gradle,  maven, Git and all others tools inside platform SDK.

third you doesn't tell why you need zsh

Fourth you can add this on CMD line when run ide if needed

I continue to not see any reason that a java or Kaitlin developer need spawn

**Comment by cardil** [comment]
Mostly, I just want my zsh set up!

But also, I have git sigs set up on my machine, not on the containerized shell. Also, IntelliJ Ultimate isn't just for Java. I use it for Golang, Rust, and Zig. Even for Java stuff, I still want my terminal to work with proxy settings, maven setting within "my" homedir, and lots of other stuff.

**Comment by xanscale** [comment]
JetBrains has numerous IDEs, each for specific language [JetBrains IDEs](https://flathub.org/apps/collection/developer/JetBrains%20s.r.o./1), i don't think we should consider IDEA to works with all.

about home dire, it works even without spawn due to standard system visibility to your home, so proxy settings and maven settings should works without spawn

about "first-run.txt", i mean that it's just a file and actually is outdated (for my opinion)

flatpak spawn broke the flatpak sandbox and his principles. it's suggested to remove if is not strictly necessary:


> finish-args-flatpak-spawn-access
> Exceptions allowed: Yes, on a case-by-case basis
> 
> The [finish-args](https://docs.flatpak.org/en/latest/manifests.html#finishing) in the manifest has --talk-name=org.freedesktop.Flatpak or --talk-name=org.freedesktop.Flatpak.*.
> 
> This allows applications to launch arbitrary commands on the host and is restricted and granted on a case-by-case basis.
> 
> This must not be used unless absolutely necessary and when no existing solutions using Flatpak or [portals](https://flatpak.github.io/xdg-desktop-portal/docs/) exist.

i think that all of the normal use of IDEA can works without it, and for the rare cases you need it you can use external terminal.

for my opinion the bug are inside first-run.txt that should be updated

**Comment by cardil** [comment]
Please see the official supported list of languages IntelliJ IDEA Ultimate supports: https://www.jetbrains.com/products/compare/?product=idea&product=idea-ce

Your statement may be true for the community version, or other JetBrains IDE, but it's not true for the Ultimate version.

**Comment by xanscale** [comment]
@cardil you don't need "spawn", as example to use php in IDEA just add flatpak php extension.

**Comment by cardil** [comment]
> @xanscale: you need just to make a switch in your brain and instead of use your OS you need to use flatpak environment

You are effectively saying I should use those:

Children bike side wheels

Sorry, This is a fricking **IDE**, and I know what I'm doing!

I just want to use my environment, not the sandbox one!

**Comment by xanscale** [comment]
@cardil look to my PL, you can add the permission when launch the IDE and made it permanent.

PS i want to run every command as root, i will ask to debian to made root the default user

**Comment by cardil** [comment]
> @xanscale: look to my PL, you can add the permission when launch the IDE and made it permanent.

I already added it using the [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) tool. However, I still think this permission should be added to this kind of application - designed for power-users.

If you still, don't want to add the permission, at least document this properly - I guess #229 is going into that direction.

**Pull request closed without merging**
